#!/usr/bin/env node
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'vendor/phosphor');
const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets/regular';
const WANT = ['github-logo', 'arrow-up-right', 'copy', 'check', 'file-text', 'text-aa', 'wallet', 'info', 'quotes'];
await mkdir(OUT, { recursive: true });
const glyphs = {};
for (const name of WANT) {
  const res = await fetch(`${BASE}/${name}.svg`);
  if (!res.ok) throw new Error(`Could not fetch ${name}: ${res.status}`);
  const svg = await res.text();
  const body = svg.replace(/<\?xml[\s\S]*?\?>/g, '').replace(/<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/fill="#([0-9a-f]{3,8})"/gi, 'fill="currentColor"').trim();
  glyphs[name] = body;
  await writeFile(resolve(OUT, `${name}.svg`), svg);
}
const license = await fetch('https://raw.githubusercontent.com/phosphor-icons/core/main/LICENSE');
await writeFile(resolve(OUT, 'LICENSE'), await license.text());
await writeFile(resolve(ROOT, 'src/lib/phosphor.ts'), `// GENERATED by scripts/icons.mjs from ${BASE}\nexport const GLYPH: Record<string, string> = ${JSON.stringify(glyphs, null, 1)};\nexport type GlyphName = keyof typeof GLYPH;\n`);
console.log(`wrote ${WANT.length} Phosphor Regular glyphs`);
