import { PRODUCT } from '@/lib/product';
import Link from 'next/link';

const GEMINI_EXTENSIONS = 'https://github.com/google-gemini/gemini-cli/blob/main/docs/extensions/reference.md';
const PRODUCT_README = `${PRODUCT.repo}/blob/main/README.md`;
const MANIFEST = `${PRODUCT.repo}/blob/main/gemini-extension.json`;

export const metadata = { title: 'How to install ParseRail for Gemini CLI', description: 'Install and verify the ParseRail Gemini CLI extension, including its API-key setting and restart step.', alternates: { canonical: `https://${PRODUCT.host}/install` } };

export default function InstallGuide() {
  return <div className="site-shell guide-shell">
    <header className="masthead"><Link className="brand" href="/"><span className="brand-mark">◈</span><span>{PRODUCT.name}</span></Link><span className="crumb">INSTALL GUIDE</span><nav><Link href="/">Register</Link><a href="#steps">Steps</a><a href="#verify">Verify</a></nav></header>
    <main>
      <section className="content-grid intro guide-hero"><div className="rail"><span className="eyebrow">GEMINI CLI / PROCEDURE</span><span className="rail-note">READ FIRST<br />UPDATED 2026-10-02</span></div><div className="lead"><h1>How do you install ParseRail for Gemini CLI?</h1><p>Run the GitHub install command in a terminal, provide the ParseRail API key when Gemini CLI asks for it, then restart Gemini CLI and confirm the extension appears in the extension list.</p><div className="install-box"><span className="prompt">$</span><code>{PRODUCT.install}</code></div><p className="install-note">This guide reflects the ParseRail repository and Gemini CLI extension reference fetched on 2026-10-02.</p></div></section>
      <section id="steps" className="section content-grid"><div className="rail"><span className="section-no">01</span><span className="eyebrow">PROCEDURE</span><span className="rail-note">THREE CHECKS<br />FROM SOURCE</span></div><div className="section-main"><div className="section-head"><h2>What are the installation steps?</h2><span>terminal → setting → restart</span></div><ol className="guide-steps"><li><strong>Install from the repository.</strong><p>Run <code>{PRODUCT.install}</code> outside Gemini CLI&apos;s interactive mode. Gemini CLI&apos;s reference says the install command accepts a GitHub URL or local path, and GitHub installs require Git. <a href={GEMINI_EXTENSIONS}>Read the Gemini CLI reference.</a></p></li><li><strong>Enter the API key.</strong><p>When the installer prompts for settings, provide the ParseRail API key. The extension manifest declares the setting as <code>PARSERAIL_API_KEY</code> and marks it sensitive. <a href={MANIFEST}>Read the manifest.</a></p></li><li><strong>Restart the session.</strong><p>Close and reopen Gemini CLI after installation or configuration. The Gemini CLI reference says extension management changes take effect after restart.</p></li></ol></div></section>
      <section id="verify" className="section content-grid"><div className="rail"><span className="section-no">02</span><span className="eyebrow">VERIFY</span><span className="rail-note">CONFIRM<br />THE ROUTE</span></div><div className="section-main"><div className="section-head"><h2>How do you verify the extension?</h2><span>one command</span></div><p className="guide-answer">Run <code>gemini extensions list</code> in a terminal, or run <code>/extensions list</code> inside Gemini CLI. Gemini CLI documents both commands for checking installed extensions; the interactive slash command is the safe in-session check. Then ask Gemini to use a ParseRail document tool with one source such as a file URL, text, or base64 file input.</p><div className="callout"><p><strong>What this extension registers:</strong> the ParseRail MCP server, the bundled <code>GEMINI.md</code> context file, and the sensitive <code>PARSERAIL_API_KEY</code> setting. The product repository&apos;s README contains the install command and the manifest is the source for the registration details. <a href={PRODUCT_README}>README</a> · <a href={MANIFEST}>manifest</a></p></div></div></section>
    </main>
    <footer className="footer"><div className="footer-top"><span>ParseRail for Gemini CLI.</span><Link href="/">Back to the extension register</Link></div><div className="footer-bottom"><span>Sources fetched 2026-10-02 · Gemini CLI reference · ParseRail README · extension manifest</span></div></footer>
  </div>;
}
